Update wrapper

diff --git a/cb/images/default/cb-wrapper b/cb/images/default/cb-wrapper
--- a/cb/images/default/cb-wrapper
+++ b/cb/images/default/cb-wrapper
@@ -1,3 +1,26 @@
 #!/bin/sh
 set -e
-echo $@
+
+DSC=$1
+shift
+
+if [ "x${DSC}" = "x" ]; then
+    echo "Missing DSC argument"
+    exit 1
+fi
+
+WORKDIR=$(dirname ${DSC})
+cd ${WORKDIR}
+
+finish() {
+    if [ -e /build/build/ ]; then
+        rm -rf /build/build/
+    fi
+}
+trap finish EXIT
+
+# drop privs
+dpkg-source -x ${DSC} build
+cd build
+mk-build-deps -r -i -t "apt-get -y --no-install-recommends"
+dpkg-buildpackage $@
